# JavaScript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#

version: 2.1

executors:
  node-executor:
    working_directory: ~/repo
    docker:
      - image: circleci/node:13-stretch
  trusty-executor:
    working_directory: ~/repo
    docker:
      - image: buildpack-deps:trusty
    shell: /bin/bash

jobs:
  build:
    executor: node-executor
    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: export NODE_ENV="dev"
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: export NODE_ENV="production"
      - run: yarn run build

  
  deploy:
    executor: node-executor
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "1c:4a:6a:10:1f:74:db:a9:70:34:de:9e:08:cd:25:c6"
      - run: 
          command: ssh -o "StrictHostKeyChecking no" ${SSH_ADDR} '/bin/bash -l -c "cd forest-calculator && git pull && yarn run build-update && forever stop forest-calculator || true && forever start ../forever/forest-calculator.json"'

workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            branches:
              only:
                - deploy
      - deploy:
          requires:
            - build
